kind: pipeline
name: check
type: docker

trigger:
  ref:
    - refs/heads/**

steps:
  - name: install
    image: node:20.13.0
    commands:
      - yarn

  - name: check
    image: node:20.13.0
    commands:
      - yarn format
      - yarn lint
      - yarn check-types

---
kind: pipeline
name: publish
type: docker

trigger:
  ref:
    - refs/heads/master
    - refs/tags/*

steps:
  - name: install
    image: node:20.13.0
    commands:
      - yarn
    when:
      event:
        - tag

  - name: auth
    image: robertstettner/drone-npm-auth
    settings:
      token:
        from_secret: NPM_TOKEN
    when:
      event:
        - tag

  - name: publish
    image: node:20.13.0
    commands:
      - yarn release
    when:
      event:
        - tag
